apiVersion: 'sparkoperator.k8s.io/v1beta2'
kind: SparkApplication
metadata:
  name: levietnam-job
  namespace: analytic
spec:
  type: Python
  pythonVersion: '3'
  mode: cluster
  image: 'namlv19970701/spark-job-test:v1.0.1'
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///home/workspace/main.py
  sparkVersion: '3.5.3'
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    coreLimit: '1024m'
    memory: '512m'
    serviceAccount: levietnam
    envVars:
      NAME: "levietnam"
  executor:
    cores: 1
    instances: 6
    memory: '512m'
