---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ingress-airflow-tls-issuer
  namespace: analytics
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-airflow-tls-cert
  namespace: analytics
spec:
  secretName: ingress-airflow-tls
  issuerRef:
    name: ingress-airflow-tls-issuer
    kind: Issuer
  commonName: airflow.levietnam.local