---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ingress-rancher-tls-issuer
  namespace: cattle-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-rancher-tls-cert
  namespace: cattle-system
spec:
  secretName: ingress-rancher-tls
  issuerRef:
    name: ingress-rancher-tls-issuer
    kind: Issuer
  commonName: rancher.levietnam.local